// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gschatbot.api.Data;

#nullable disable

namespace gschatbot.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621000905_AddUsuario")]
    partial class AddUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("gschatbot.api.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EspecialistaId")
                        .HasColumnType("int");

                    b.Property<int>("HorarioConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("NotasCliente")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlanoAssistenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EspecialistaId");

                    b.HasIndex("HorarioConsultaId")
                        .IsUnique();

                    b.HasIndex("PlanoAssistenciaId");

                    b.HasIndex("Status");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("gschatbot.api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("gschatbot.api.Models.ClienteNumero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Principal")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("ClienteNumeros");
                });

            modelBuilder.Entity("gschatbot.api.Models.ClientePlano", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("PlanoAssistenciaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCarteirinha")
                        .HasColumnType("longtext");

                    b.HasKey("ClienteId", "PlanoAssistenciaId");

                    b.HasIndex("PlanoAssistenciaId");

                    b.ToTable("ClientePlanos");
                });

            modelBuilder.Entity("gschatbot.api.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("gschatbot.api.Models.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("gschatbot.api.Models.Especialista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Especialistas");
                });

            modelBuilder.Entity("gschatbot.api.Models.EspecialistaMetodoPagamento", b =>
                {
                    b.Property<int>("EspecialistaId")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPagamentoId")
                        .HasColumnType("int");

                    b.HasKey("EspecialistaId", "MetodoPagamentoId");

                    b.HasIndex("MetodoPagamentoId");

                    b.ToTable("EspecialistaMetodosPagamento");
                });

            modelBuilder.Entity("gschatbot.api.Models.EspecialistaPlano", b =>
                {
                    b.Property<int>("EspecialistaId")
                        .HasColumnType("int");

                    b.Property<int>("PlanoAssistenciaId")
                        .HasColumnType("int");

                    b.HasKey("EspecialistaId", "PlanoAssistenciaId");

                    b.HasIndex("PlanoAssistenciaId");

                    b.ToTable("EspecialistaPlanos");
                });

            modelBuilder.Entity("gschatbot.api.Models.HistoricoMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetadadosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RemetenteId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoMensagens");
                });

            modelBuilder.Entity("gschatbot.api.Models.HorarioConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataConsulta")
                        .HasColumnType("date");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialistaId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("EspecialistaId", "DataConsulta");

                    b.ToTable("HorariosConsulta");
                });

            modelBuilder.Entity("gschatbot.api.Models.MetodoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MetodosPagamento");
                });

            modelBuilder.Entity("gschatbot.api.Models.PlanoAssistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlanosAssistencia");
                });

            modelBuilder.Entity("gschatbot.api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("gschatbot.api.Models.Agendamento", b =>
                {
                    b.HasOne("gschatbot.api.Models.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.Especialista", "Especialista")
                        .WithMany("Agendamentos")
                        .HasForeignKey("EspecialistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.HorarioConsulta", "HorarioConsulta")
                        .WithOne("Agendamento")
                        .HasForeignKey("gschatbot.api.Models.Agendamento", "HorarioConsultaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.PlanoAssistencia", "PlanoAssistencia")
                        .WithMany()
                        .HasForeignKey("PlanoAssistenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Especialista");

                    b.Navigation("HorarioConsulta");

                    b.Navigation("PlanoAssistencia");
                });

            modelBuilder.Entity("gschatbot.api.Models.ClienteNumero", b =>
                {
                    b.HasOne("gschatbot.api.Models.Cliente", "Cliente")
                        .WithMany("Numeros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("gschatbot.api.Models.ClientePlano", b =>
                {
                    b.HasOne("gschatbot.api.Models.Cliente", "Cliente")
                        .WithMany("Planos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.PlanoAssistencia", "PlanoAssistencia")
                        .WithMany("Clientes")
                        .HasForeignKey("PlanoAssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PlanoAssistencia");
                });

            modelBuilder.Entity("gschatbot.api.Models.Especialista", b =>
                {
                    b.HasOne("gschatbot.api.Models.Especialidade", "Especialidade")
                        .WithMany("Especialistas")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("gschatbot.api.Models.EspecialistaMetodoPagamento", b =>
                {
                    b.HasOne("gschatbot.api.Models.Especialista", "Especialista")
                        .WithMany("MetodosPagamento")
                        .HasForeignKey("EspecialistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.MetodoPagamento", "MetodoPagamento")
                        .WithMany("Especialistas")
                        .HasForeignKey("MetodoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialista");

                    b.Navigation("MetodoPagamento");
                });

            modelBuilder.Entity("gschatbot.api.Models.EspecialistaPlano", b =>
                {
                    b.HasOne("gschatbot.api.Models.Especialista", "Especialista")
                        .WithMany("PlanosAtendidos")
                        .HasForeignKey("EspecialistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.PlanoAssistencia", "PlanoAssistencia")
                        .WithMany("Especialistas")
                        .HasForeignKey("PlanoAssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialista");

                    b.Navigation("PlanoAssistencia");
                });

            modelBuilder.Entity("gschatbot.api.Models.HistoricoMensagem", b =>
                {
                    b.HasOne("gschatbot.api.Models.Agendamento", "Agendamento")
                        .WithMany("HistoricoMensagens")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("gschatbot.api.Models.Cliente", "Cliente")
                        .WithMany("HistoricoMensagens")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("gschatbot.api.Models.HorarioConsulta", b =>
                {
                    b.HasOne("gschatbot.api.Models.Endereco", "Endereco")
                        .WithMany("HorariosConsulta")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gschatbot.api.Models.Especialista", "Especialista")
                        .WithMany("HorariosConsulta")
                        .HasForeignKey("EspecialistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Especialista");
                });

            modelBuilder.Entity("gschatbot.api.Models.Agendamento", b =>
                {
                    b.Navigation("HistoricoMensagens");
                });

            modelBuilder.Entity("gschatbot.api.Models.Cliente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("HistoricoMensagens");

                    b.Navigation("Numeros");

                    b.Navigation("Planos");
                });

            modelBuilder.Entity("gschatbot.api.Models.Endereco", b =>
                {
                    b.Navigation("HorariosConsulta");
                });

            modelBuilder.Entity("gschatbot.api.Models.Especialidade", b =>
                {
                    b.Navigation("Especialistas");
                });

            modelBuilder.Entity("gschatbot.api.Models.Especialista", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("HorariosConsulta");

                    b.Navigation("MetodosPagamento");

                    b.Navigation("PlanosAtendidos");
                });

            modelBuilder.Entity("gschatbot.api.Models.HorarioConsulta", b =>
                {
                    b.Navigation("Agendamento")
                        .IsRequired();
                });

            modelBuilder.Entity("gschatbot.api.Models.MetodoPagamento", b =>
                {
                    b.Navigation("Especialistas");
                });

            modelBuilder.Entity("gschatbot.api.Models.PlanoAssistencia", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Especialistas");
                });
#pragma warning restore 612, 618
        }
    }
}
